const $=s=>document.querySelector(s); const tabs=[...document.querySelectorAll('.tab')];
const state={music:JSON.parse(localStorage.getItem('rhs_music')||'[]'),links:JSON.parse(localStorage.getItem('rhs_links')||'[]'),history:JSON.parse(localStorage.getItem('rhs_login_history')||'[]')};
function save(){localStorage.setItem('rhs_music',JSON.stringify(state.music));localStorage.setItem('rhs_links',JSON.stringify(state.links));localStorage.setItem('rhs_login_history',JSON.stringify(state.history));}
function cleanHistory(){const n=Date.now();state.history=state.history.filter(x=>n-x.ts<86400000);save();}
function show(name){tabs.forEach(x=>x.classList.toggle('active',x.id===name));document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));$('#pageTitle').textContent={overview:'Visão geral',music:'Músicas',links:'Canais & grupos',history:'Histórico 24h',settings:'Segurança'}[name]||'Painel';}
function render(){cleanHistory();$('#musicCount').textContent=state.music.length;$('#linkCount').textContent=state.links.length;$('#musicList').innerHTML=state.music.map((x,i)=>`<div class="row"><div><b>${escapeHtml(x.name)}</b><small>${escapeHtml(x.source)}</small></div><button data-del="m:${i}">Excluir</button></div>`).join('')||'<div class="empty">Nenhuma música cadastrada.</div>';$('#historyList').innerHTML=state.history.map(x=>`<div class="row"><div><b>${escapeHtml(x.email)}</b><small>${new Date(x.ts).toLocaleString('pt-BR')}</small></div><span>LOGIN</span></div>`).join('')||'<div class="empty">Nenhum login nas últimas 24 horas neste navegador.</div>';}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
async function session(){const r=await fetch('/api/admin/session');return r.ok&&(await r.json()).ok;}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const msg=$('#loginMsg');msg.textContent='Entrando...';const email=$('#email').value.trim().toLowerCase(),password=$('#password').value;const r=await fetch('/api/admin/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!d.ok){msg.textContent=d.error||'Falha no login';return}state.history.unshift({email:d.email,ts:Date.now()});save();$('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#adminEmail').textContent=d.email;render();});
$('#logout').addEventListener('click',async()=>{await fetch('/api/admin/logout',{method:'POST'});location.reload()});
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>show(b.dataset.tab));document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>show(b.dataset.open));
$('#musicForm').addEventListener('submit',e=>{e.preventDefault();const name=$('#musicName').value.trim();const url=$('#musicUrl').value.trim();const file=$('#musicFile').files[0];if(!url&&!file)return alert('Informe um link ou selecione um arquivo.');state.music.unshift({name,source:file?`Arquivo: ${file.name}`:url});save();e.target.reset();render();});
$('#musicList').addEventListener('click',e=>{const b=e.target.closest('[data-del]');if(!b)return;const [t,i]=b.dataset.del.split(':');if(t==='m')state.music.splice(Number(i),1);save();render()});
$('#linkForm').addEventListener('submit',async e=>{e.preventDefault();const url=$('#communityUrl').value.trim();const out=$('#linkResult');out.innerHTML='<div class="loading">Buscando informações públicas...</div>';try{const r=await fetch('/api/community/resolve?url='+encodeURIComponent(url));const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Não foi possível obter a prévia.');state.links.unshift({url,name:d.name,image:d.image});save();render();out.innerHTML=`<div class="preview"><img src="${d.image||'/assets/logo.svg'}" onerror="this.src='/assets/logo.svg'"><div><b>${escapeHtml(d.name||'Comunidade')}</b><small>${escapeHtml(url)}</small></div></div>`}catch(err){out.innerHTML='<div class="error">'+escapeHtml(err.message)+'</div>'}});
(async()=>{if(await session()){$('#login').classList.add('hidden');$('#app').classList.remove('hidden');render()}})();
